### ISSUE TITLE
java.lang.IllegalArgumentException: Session with same ID already exists

### ISSUE THREAD

**Issue by O2PLUSADMIN** [pocmo/iceant#5]
Hello, i am a beginner in android programming as a hobbyist following your youtube channel. Sometimes the browser simply crashes without any reason. I cant figure out why. i have attached my code and error below.

**Error :** 

Caused by java.lang.IllegalArgumentException: Session with same ID already exists
       at mozilla.components.browser.session.LegacySessionManager.addInternal(LegacySessionManager.kt:98)
       at mozilla.components.browser.session.LegacySessionManager.addInternal$default(LegacySessionManager.kt:95)
       at mozilla.components.browser.session.LegacySessionManager.add(LegacySessionManager.kt:86)
       at mozilla.components.browser.session.SessionManager.add(SessionManager.kt:129)
       at mozilla.components.browser.session.SessionManager.add$default(SessionManager.kt:104)
       at com.system37.o2plus.Render.onCreate(Render.kt:92)
       at android.app.Activity.performCreate(Activity.java:7852)
       at android.app.Activity.performCreate(Activity.java:7841)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3357)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3521)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2128)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7711)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### My Code

package com.system37.o2plus

import android.content.Context
//import android.content.Intent
import android.content.pm.ActivityInfo
import android.content.pm.ApplicationInfo
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.os.Build
import android.os.Bundle
import android.provider.Settings
import android.util.AttributeSet
import android.view.View
import android.view.WindowManager
//import android.view.autofill.AutofillManager
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.scottyab.rootbeer.RootBeer
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.android.synthetic.main.activity_render.*
import mozilla.components.browser.session.Session
import mozilla.components.browser.session.SessionManager
import mozilla.components.browser.state.store.BrowserStore
import mozilla.components.concept.engine.Engine
import mozilla.components.concept.engine.EngineView
import mozilla.components.feature.downloads.DownloadsFeature
import mozilla.components.feature.downloads.DownloadsUseCases
import mozilla.components.feature.downloads.manager.FetchDownloadManager
import mozilla.components.feature.session.FullScreenFeature
import mozilla.components.feature.session.SessionFeature
import mozilla.components.feature.session.SessionUseCases
import java.net.Proxy
import java.net.ProxySelector
import java.net.URI
import java.util.*
import javax.inject.Inject
import kotlin.concurrent.timerTask
import kotlin.system.exitProcess

@AndroidEntryPoint
class Render : AppCompatActivity() {
    @Inject lateinit var engine: Engine
    @Inject lateinit var store: BrowserStore
    @Inject lateinit var sessionManager: SessionManager
    @Inject lateinit var session: Session

    private lateinit var sessionUseCases: SessionUseCases
    private lateinit var sessionFeature: SessionFeature
    private lateinit var feature: FullScreenFeature
    private lateinit var downloadsFeature: DownloadsFeature

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_render)
        val intent = intent
        val url = intent.getStringExtra("url")
        supportActionBar?.hide()

        window.setFlags(
                WindowManager.LayoutParams.FLAG_SECURE,
                WindowManager.LayoutParams.FLAG_SECURE)
        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT

        proxy_check()

        sessionUseCases = SessionUseCases(store, sessionManager)
        val downloadUseCases = DownloadsUseCases(store)

        sessionFeature = SessionFeature(
                store,
                sessionUseCases.goBack,
                findViewById<View>(R.id.engineView) as EngineView
        )

        feature = FullScreenFeature(
                store,
                sessionUseCases,
                fullScreenChanged = ::fullScreenChanged
        )

        val device_valid = (!adb_status() && !apk_debuggable() && display_flag() && !device_root() && !checkEmulator())

        if (url != null) {
            if (device_valid && !isproxy(this)) {
                app_tamper_check()
                this.session.url = url
            }
        }
        
        sessionManager.add(
            session
        )

        session.register(object : Session.Observer {
            override fun onProgress(session: Session, progress: Int){
                if (progress == 100){
                    if (progressBar_render.visibility == View.VISIBLE){
                        progressBar_render.visibility = View.GONE
                        window.clearFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE)
                    }
                } else {
                    if (progressBar_render.visibility == View.GONE){
                        window.setFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE, WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE)
                        progressBar_render.visibility = View.VISIBLE
                    }
                }
            }
        })

        downloadsFeature = DownloadsFeature(
                applicationContext,
                store,
                downloadUseCases,
                onNeedToRequestPermissions = { permissions ->
                    requestPermissions(permissions, 1)
                },
                downloadManager = FetchDownloadManager(
                        applicationContext,
                        store,
                        DownloadService::class
                ),
                fragmentManager = supportFragmentManager
        )

        lifecycle.addObserver(sessionFeature)
        lifecycle.addObserver(feature)
        lifecycle.addObserver(downloadsFeature)

    }

**Comment by O2PLUSADMIN** [comment]
for your benefit Line 92 is

        sessionManager.add(
            session
        )

The error seems to begin here. Any help is much appreciated !!!

**Comment by pocmo** [comment]
Hey @O2PLUSADMIN! :)

This error indicates that you are adding the same tab twice (two tabs have the same ID). This crash was added deliberately to prevent a bunch of accidental code errors.

In the cove above I see that you are calling `SessionManager.add` from `onCreate()`. This method could get called more than once (e.g. by default when you rotate the phone to landscape then it will recreate the activity, [see docs about the activity lifecycyle for more](https://developer.android.com/guide/components/activities/activity-lifecycle)). I don't see where you create `session` (is it getting injected by dagger-hilt?), but if that is always the same object then you may end up adding the same `session` again and it will crash.

It depends on what you actually want to achieve, but here are some ideas that may help you:
* If this is a tab you just always want to have when the app is launched then maybe consider adding it directly where you create `SessionManager`. Then it only gets created once.
* If it needs to happen in the activity and if it's always the same then consider checking whether the tab is already there (e.g. `findSessionById`).
* If you intent to always add a new tab here, no matter whether there's already one, then do not inject a `Session` singleton, but always create a fresh one.

Hope that helps :)
